name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Full Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~ || exit 1
          rm -rf PRTIMES_Hackathon
          #Backend
          git clone https://github.com/shkrn/PRTIMES_Hackathon.git
          cd PRTIMES_Hackathon/webapp
          docker compose down -v || true
          docker compose up -d --build
          echo "Backend Deploy complete! Check http://$(curl -s ifconfig.me):8080"
          #Frontend
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd nextjs
          npm ci
          EC2_IP=$(curl -s ifconfig.me)
          export NEXT_PUBLIC_API_BASE_URL="http://${EC2_IP}:8080"
          nohup npm run dev > nextjs.log 2>&1 &
          echo "Frontend Deploy complete! Check http://$(curl -s ifconfig.me):3000"


